### PR TITLE
Constrain react-redux to <6

### PR DESCRIPTION
**Pull request by kahwee**
Adding version constraints since react-redux v6 isn't support.

### CODE REVIEW

**Comment by ardok** [comment]
Just wondering, why isn't react-redux v6+ supported?

**Comment by ardok** [comment]
@kahwee @KevinGrandon ping

**Comment by KevinGrandon** [comment]
I believe we are able to technically support it now, but there was some issues with performance in the latest release that was preventing us from upgrading. I'm not sure if there's an issue tracking this somewhere. CC @rtsao

**Comment by chirgjn** [comment]
`withRPCRedux` from `fusion-plugin-rpc-redux-react` doesn't work with a container component using `react-redux` 6

**Comment by ardok** [comment]
So, only because `withRPCRedux`?
If you don't use that, then you can use `react-redux` v6?

**Comment by chirgjn** [comment]
That's the issue that I faced, can't confirm the status of other things. It was a new project so didn't really test anything yet.

**Pull request merged**
